name: JLC Auto Sign

on:
  schedule:
    - cron: '0 8,20 * * *'  # 北京时间 4:00 和 16:00

  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Sign Script
      env:
        TOKEN_LIST: ${{ secrets.TOKEN_LIST }}
        SEND_KEY_LIST: ${{ secrets.SEND_KEY_LIST }}
      run: |
        python main.py